using System;
using NUnit.Framework;

using IO.Swagger.Api;

namespace Bybit.Api.Client.Test
{
    /// <summary>
    ///  Class for testing KlineApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class KlineApiTests
    {
        private KlineApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new KlineApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }
       
        /// <summary>
        /// Test KlineGet
        /// </summary>
        [Test]
        public void KlineGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            string symbol = "BTCUSDT";
            string interval = null;
            decimal? from = null;
            decimal? limit = null;
            var response = instance.KlineGet(symbol, interval, from, limit);
            Assert.IsInstanceOf<Object>(response, $"response is {response.GetType().FullName}");
        }
        
        /// <summary>
        /// Test KlineMarkPrice
        /// </summary>
        [Test]
        public void KlineMarkPriceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string symbol = null;
            //string interval = null;
            //int? from = null;
            //int? limit = null;
            //var response = instance.KlineMarkPrice(symbol, interval, from, limit);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
    }

}
