
using NUnit.Framework;

using IO.Swagger.Api;

namespace Bybit.Api.Client.Test
{
    /// <summary>
    ///  Class for testing MarketApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class MarketApiTests
    {
        private MarketApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new MarketApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test MarketOrderbook
        /// </summary>
        [Test]
        [TestCase("")]
        [TestCase(null)]
        [TestCase("BTCUSDT")]
        [TestCase("ETHUSDT")]
        [TestCase("DOGEUSDT")]
        [TestCase("BTCUSD")]
        [TestCase("ETHUSD")]
        [TestCase("DOGEUSD")]
        public void GetOrderbookTest(string symbol)
        {
            var response = instance.MarketOrderbook(symbol);
            Assert.IsInstanceOf<Newtonsoft.Json.Linq.JObject> (response, "response is Newtonsoft.Json.Linq.JObject");
            var jobj = (Newtonsoft.Json.Linq.JObject)response;
            var obResponse = jobj.ToObject<IO.Swagger.Model.OrderBookBase>();
            Assert.AreEqual(0, obResponse.RetCode);
            Assert.IsNotEmpty(obResponse.Result);
        }
    }

}
